name: ahadith_alzakah
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  arabic_font: ^0.0.9
  google_fonts: ^6.2.1
  supabase_flutter: ^2.9.0
  flutter_secure_storage: ^9.2.4
  connectivity_plus: ^6.1.4
  number_to_word_arabic: ^0.0.8
  archive: ^4.0.7
  windows_notification: ^1.3.0
  tray_manager: 
  window_manager: 
  system_tray:
  cron: ^0.6.2
  win32: ^5.14.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  msix: ^3.16.12

  flutter_lints: ^5.0.0
  logger: ^2.5.0
  flutter_launcher_icons: ^0.14.3
flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/backGround.webp
    - assets/opening-screen-crupped-blured.webp
    - assets/logo.png
    - assets/ic_launcher.png
    - assets/app_icon.ico
    - assets/app_icon.png

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/logo.png"
  adaptive_icon_background: "#FFFFFF" 
  adaptive_icon_foreground: "assets/logo.png"
  remove_alpha_ios: true
msix_config:
  display_name: موسوعة أحاديث الزكاة
  publisher_display_name: Islam Saeed
  identity_name: IslamSaeed.5510813C742D0
  publisher: CN=58C2FEF5-20C8-4652-9478-669C11E84A8F
  msix_version: 1.0.0.1
  architecture: x64
  logo_path: assets/logo.png
  certificate_path: D:\flutter_projects\ahadith_alzakah\signing\certificate.pfx
  certificate_password: CER9854CER
  timestamp_server: http://timestamp.sectigo.com
  capabilities: 'internetClient,backgroundTasks'
  execution_alias: موسوعة أحاديث الزكاة
  app_description: موسوعة شاملة لأحاديث الزكاة مع إشعارات يومية